<?php
use yii\helpers\Url;

$bUrl=Url::base();
$protocol = (isset($_SERVER['HTTPS'])? "https":"http");
$host=$_SERVER['SERVER_NAME'];
$url=$protocol.'://'.$host.$bUrl; 
?><!-- start textbox-with-title -->
<table width="100%" cellpadding="0" cellspacing="0" border="0" id="backgroundTable">
                                          <tr>
                                             <td style="font-family:Georgia, 'Times New Roman', Times, serif; font-size:24px;text-align:left;line-height: 24px;">
												<?php echo $main_subject;?>
												<hr/>
                                             </td>
                                          </tr>
                                          <tr>
                                             <td style="font-family:Georgia, 'Times New Roman', Times, serif; font-size:14px;text-align:left;line-height: 14px;">
												<strong><?php echo $main_header;?></strong>
												<hr/>
                                             </td>
                                          </tr>
                                          <!-- End of Title -->
                                          <!-- spacing -->
                                          <tr>
                                             <td height="5">&nbsp;</td>
                                          </tr>
                                          <!-- End of spacing -->
                                          <!-- content -->
                                          <tr>
                                             <td style="font-family: arial;font-size:14px; text-align:left;line-height:14px;">
												 
												<?php echo $main_body;?>
                                             
                                             <br /><br />
                                             </td>
                                          </tr>
                                          <!-- End of content -->
                                          <tr>
                                             <td>
											 	 <hr>
												<?php
												$linkname = $url;
												echo 'This notification was generated by IS-A-TASK.<br>
												To view your IS-A-TASK Project, visit: <a href="javascript:void(0);">'.$linkname.'</a><br>'.'To view your IS-A-TASK Project Instructions, visit: <a href="javascript:void(0);">'.$linkname.'</a>';
												?>
                                             </td>
                                          </tr>
                                          <!-- /button -->
                                          <!-- Spacing -->
                                          <tr>
                                             <td width="100%" height="20"></td>
                                          </tr>
									  
</table>