pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["about_isatask.htm","About IS-A-TASK","About IS-A-TASK Top Next IS-A-TASKTM is an eDiscovery workflow management application specifically designed to help both project managers that foc...",""],
["add_case.htm","Add Case","Add Case Top Previous Next -Select Cases node -Enter Case information -Select Add button ",""],
["add_case_contacts.htm","Add Case Contacts","Add Case Contacts Top Previous Next -Select a specific Case node. -Select Contacts tab. -Select Add button: -Select the Contacts that the user wan...",""],
["add_case_manager_team_services.htm","Add Case Manager Team Services","Add Case Manager Team Services Top Previous Next -To add Services, Select Add button under the Team Service tab. -Enter Service Name -Enter Descri...",""],
["add_case_manager_team_service_tasks.htm","Add Case Manager Team Service Tasks","Add Case Manager Team Service Tasks Top Previous Next -To add Service Tasks, Select Add button under the Service Tasks tab: -Enter Task Name. -Ent...",""],
["add_case_manager_team_service_task_subtasks.htm","Add Case Manager Team Service Task Subtasks","Add Case Manager Team Service Task Subtasks Top Add Case Manager Team Service Task Subtasks Service Task Subtasks - Optionally, each Task can cons...",""],
["add_case_preferred_rates.htm","Add Case Preferred Rates","Add Case Preferred Rates Top Previous Next ",""],
["add_client.htm","Add Client","Add Client Top Previous Next -Select Clients node -Enter Client information -Select Add button ",""],
["add_client_contacts.htm","Add Client Contacts","Add Client Contacts Top Previous Next -Select a specific Client node. -Select Add Contacts tab. -Select Add button: -Enter contact information. -S...",""],
["add_client_preferred_rates.htm","Add Client Preferred Rates","Add Client Preferred Rates Top Previous Next ",""],
["add_dropdown_item.htm","Add Dropdown Item","Add Dropdown Item Top Previous Next -Select Drop-down type -Select Add button -Enter dropdown selection value -Select Add button Note: Priority Pr...",""],
["add_form_case_manager_team_service_tasks.htm","Add Form to Case Manager Team Service Tasks","Add Form to Case Manager Team Service Tasks Top Previous Next -To add Task Form, Select a Task row in the grid under Service Tasks tab. -Select th...",""],
["add_form_operation_team_service_tasks.htm","Add Form Operation Team Service Tasks","Add Form Operation Team Service Tasks Top Previous Next -To add Task Form, Select a Task row in the grid under the Service Tasks tab. -Select the ...",""],
["add_media.htm","Add Media","Add Media Top Previous Next -Select Add New Media button -Enter Media detail information -Select Add button ",""],
["add_media_contents.htm","Add Media Contents","Add Media Contents Top Previous Next -Select the Add Contents button -Select Associated Cases Media media is associted with -Select Next button -E...",""],
["add_operation_team.htm","Add Operation Team","Add Operation Team Top Previous Next -Select Teams node header -Enter Team information -Select Add button Note: Team nodes may be dragged and drop...",""],
["add_operation_team_services.htm","Add Operation Team Services","Add Operation Team Services Top Previous Next -To add Services, Select a Team node. -Select Add button under Team Services tab. -Enter Service Nam...",""],
["add_operation_team_service_tasks.htm","Add Operation Team Service Tasks","Add Operation Team Service Tasks Top Previous Next -To add Service Tasks, Select Add button under the Service Tasks tab: -Enter Task Name. -Enter ...",""],
["add_roles.htm","Add Roles","Add Roles Top Previous Next -Select User Roles node -Enter User Role details -Note there are two types of Role Types to select: -Case Manager - se...",""],
["add_shared_pricepoints.htm","Add Shared Price Points","Add Shared Price Points Top Previous Next ",""],
["add_tax_class.htm","Add Tax Class","Add Tax Class Top Previous Next ",""],
["add_tax_code.htm","Add Tax Code","Add Tax Code Top Previous Next ",""],
["add_team_pricepoints.htm","Add Team Price Points","Add Team Price Points Top Previous Next ",""],
["add_users.htm","Add Users","Add Users Top Previous Next -Select Users node -Add User details -Select User Type: -Internal - this option is by default and categorizes the user...",""],
["administration.htm","Administration","Administration Top Previous Next The Administration Module is where the IS-A-TASK administration sets up the application environment for users to ...",""],
["application_layout.htm","Application Layout","Application Layout Top Previous Next ",""],
["application_workflow.htm","Application Workflow","Application Workflow Top Previous Next In order for all users to begin to submit project to manage and track, there are specific areas of the appl...",""],
["assignments.htm","Assignments","Assignments Top Previous Next The Assignments module lists all of the users Task and Todo assignments, displays a Today&#39;s Activity window so the u...",""],
["assignments_system_alerts.htm","Assignments System Alerts","Assignments System Alerts Top Previous Next System Alerts informs the user that new activity has been applied to their assigned projects, cases or...",""],
["billing.htm","Billing","Billing Top Previous Next ",""],
["billing_setup.htm","Billing Setup","Billing Setup Top Previous Next Team pricing must be setup in the billing module prior to using IS-A-TASK to track project cost and apply billable...",""],
["bulk_close_projects.htm","Bulk Close Projects","Bulk Close Projects Top Bulk Close Projects ",""],
["bulk_export_final_invoices.htm","Bulk Export Final Invoices","Bulk Export Final Invoices Top Previous Next ",""],
["bulk_reopen_projects.htm","Bulk Reopen Projects","Bulk Reopen Projects Top Bulk Reopen Projects ",""],
["cases_billable_items.htm","Cases Billable Items","Cases Task Billable Items Top Previous Next ",""],
["cases_custodian_subtasks.htm","Cases Custodian Subtasks","Cases Task Custodian Subtasks Top Previous Next ",""],
["cases_todo_items.htm","Cases ToDo Items","Cases Task ToDo Items Top Previous Next ",""],
["case_assigned_users.htm","Case Assigned Users","Case Assigned Users Top Previous Next Assigned Users lists all users that are assigned to the Case: ",""],
["case_assignments_status_grid.htm","Case Assignments Status Grid","Case Assignments Status Grid Top Previous Next My Case Assignments tab indicates the logged in user&#39;s assignments that relate to Case Manager team...",""],
["case_budget.htm","Case Budget","Case Budget Top Previous Next ",""],
["case_contacts.htm","Case Contacts","Case Contacts Top Previous Next The Case Contacts tab allows the user to associated Client contacts to a case. Since a case can have a combination...",""],
["case_documents.htm","Case Documents","Case Documents Top Previous Next ",""],
["case_management.htm","Case Management","Case Management Top Previous Next Case Management is a submodule designed to manage all of your clients cases: -Add Case -Remove Case -Edit Case -...",""],
["case_manager_team.htm","Case Manager Team","Case Manager Team Top Previous Next Case Manager Team Workflow - The Case Manager Team is already created by default. Each Case that is created wi...",""],
["case_manager_team_assigned_users.htm","Case Manager Team Assigned Users","Case Manager Team Assigned Users Top Previous Next Assigned Users lists all users that are assigned to the Case Manager Role Type: ",""],
["case_manager_team_services.htm","Case Manager Team Services","Case Manager Team Services Top Previous Next Case Manager Services - A Service is a subgroup within a team that have Tasks that are unique to the ...",""],
["case_manager_team_service_tasks.htm","Case Manager Team Service Tasks","Case Manager Team Service Tasks Top Previous Next Case Manager Services Tasks - A Service Task is an activity that needs to be accomplished within...",""],
["case_manager_team_service_task_forms.htm","Case Manager Team Service Task Forms","Case Manager Team Service Task Forms Top Previous Next Service Tasks Instruction Forms - Optionally, in order for a Team to complete a Task, some ...",""],
["case_manager_team_service_task_subtasks.htm","Case Manager Team Service Task Subtasks","Case Manager Team Service Task Subtasks Top Case Manager Team Service Task Subtasks ",""],
["case_preferred_pricing.htm","Case Preferred Pricing","Case Preferred Pricing Top Previous Next ",""],
["case_projects.htm","Case Projects","Case Projects Top Previous Next The Case Project submodule is where the user submits projects, change projects, access saved projects, remove proj...",""],
["case_project_grid.htm","Case Project Grid","Case Project Grid Top Previous Next The Case Project Grid lists all of the projects that are submitted in the case. The user may select any row in...",""],
["case_project_transaction_activity.htm","Case Project Transaction Activity","Case Project Transaction Activity Top Previous Next ",""],
["case_reports.htm","Case Reports","Case Reports Top Previous Next ",""],
["case_task_assignments.htm","Case Task Assignments","Case Task Assignments Top Previous Next The Case Task Assignments section allows users to assign or transition tasks to users in Track Project sub...",""],
["case_task_status.htm","Case Task Status","Case Task Status Top Previous Next ",""],
["change_case_project.htm","Change Case Project","Change Case Project Top Previous Next The Change Case Project section allows the user to change the project after it has been submitted. Project c...",""],
["change_password.htm","Change Password","Change Password Top Previous Next -Select the Options icon -Select Change Password -Enter new password details -Select Update ",""],
["client_assigned_users.htm","Client Assigned Users","Client Assigned Users Top Previous Next Assigned Users lists all users that are assigned to the Client: ",""],
["client_case_setup.htm","Client/Case Setup","Client/Case Setup Top Previous Next Client and their associated cases must be setup in the Administration module prior to using IS-A-TASK: The Cli...",""],
["client_contacts.htm","Client Contacts","Client Contacts Top Previous Next Client Contacts is an area to manage specific client contacts. All contacts associated across all cases are stor...",""],
["client_management.htm","Client Management","Client Management Top Previous Next The Client Management is a submodule designed to manage all of your clients: - Add Client - Remove Client - Ed...",""],
["client_preferred_pricing.htm","Client Preferred Pricing","Client Preferred Pricing Top Previous Next ",""],
["closed_case_projects.htm","Closed Case Projects","Closed Case Projects Top Previous Next ",""],
["close_case_project.htm","Close Case Project","Close Case Project Top Previous Next ",""],
["copy_case_folder_file.htm","Copy Case Folder/File","Copy Case Folder/File Top Previous Next ",""],
["copy_team_folder_file.htm","Copy Team Folder/File","Copy Team Folder/File Top Previous Next ",""],
["create_case_folder.htm","Create Case Folder","Create Case Folder Top Previous Next ",""],
["create_team_folder.htm","Create Team Folder","Create Team Folder Top Previous Next ",""],
["cut_case_folder_file.htm","Cut Case Folder/File","Cut Case Folder/File Top Previous Next ",""],
["cut_team_folder_file.htm","Cut Team Folder/File","Cut Team Folder/File Top Previous Next ",""],
["delete_case_folder_file.htm","Delete Case Folder/File","Delete Case Folder/File Top Previous Next ",""],
["delete_final_invoices.htm","Delete Final Invoices","Delete Final Invoices Top Previous Next ",""],
["delete_media.htm","Delete Media","Delete Media Top Previous Next -Select one or more Media rows -Select Delete Media node Note: If the Media is already associated with a project, i...",""],
["delete_saved_case_projects.htm","Delete Saved Case Projects","Delete Saved Case Projects Top Previous Next -Select the Saved Project button on main Case Projects screen -Select a specific row in the grid disp...",""],
["delete_saved_invoices.htm","Delete Saved Invoices","Delete Saved Invoices Top Previous Next ",""],
["delete_team_folder_file.htm","Delete Team Folder/File","Delete Team Folder/File Top Previous Next ",""],
["discount_review_invoices.htm","Discount Review Invoices","Discount Review Invoices Top Previous Next ",""],
["dynamic_filters.htm","Dynamic Filters","Dynamic Filters Top Previous Next The Dynamic Filters submodule allows user to perform filters on specific criteria that is listed in the left sec...",""],
["edit_case.htm","Edit Case","Edit Case Top Previous Next -Select a Case node. -Edit Case information. -Select Update button under Edit Case tab. ",""],
["edit_case_contacts.htm","Edit Case Contacts","Edit Case Contacts Top Edit Case Contacts ",""],
["edit_case_folder_file_permissions.htm","Edit Case Folder/File Permissions","Edit Case Folder/File Permissions Top Previous Next ",""],
["edit_case_manager_team_services.htm","Edit Case Manager Team Services","Edit Case Manager Team Services Top Previous Next -To edit a Service, check the service row item in the grid under the Team Services tab. -Select ...",""],
["edit_case_manager_team_service_tasks.htm","Edit Case Manager Team Service Tasks","Edit Case Manager Team Service Tasks Top Previous Next -To edit Services Tasks, Select Edit button under the Service Tasks tab: -Edit Task Name. -...",""],
["edit_case_manager_team_service_task_subtasks.htm","Edit Case Manager Team Service Task Subtasks","Edit Case Manager Team Service Task Subtasks Top Edit Case Manager Team Service Task Subtasks ",""],
["edit_case_preferred_rates.htm","Edit Case Preferred Rates","Edit Case Preferred Rates Top Previous Next ",""],
["edit_client.htm","Edit Client","Edit Client Top Previous Next -Select a Client node. -Edit Client information. -Select Update button under Edit Client tab. ",""],
["edit_client_contacts.htm","Edit Client Contacts","Edit Client Contacts Top Previous Next -Select a specific Client node. -Select Add Contacts tab. -Select a Contact row in the grid. -Select Edit b...",""],
["edit_client_preferred_rates.htm","Edit Client Preferred Rates","Edit Client Preferred Rates Top Previous Next ",""],
["edit_dropdown_item.htm","Edit Dropdown Item","Edit Dropdown Item Top Previous Next -Select Drop-down type -Select a dropdown type value -Select Edit button -Edit dropdown selection value -Sele...",""],
["edit_form_case_manager_team_service_tasks.htm","Edit Form to Case Manager Team Service Tasks","Edit Form to Case Manager Team Service Tasks Top Previous Next -To edit Task Form, Select a Task row in the grid under the Service Tasks tab. -Sel...",""],
["edit_form_operation_team_service_tasks.htm","Edit Form Operation Team Service Tasks","Edit Form Operation Team Service Tasks Top Previous Next -To edit Task Form, Select a Task row in the grid under the Service Tasks tab. -Select th...",""],
["edit_media.htm","Edit Media","Edit Media Top Previous Next -Select a specific Media row -Select Edit Media node -Edit the Media detail information -Select Update button ",""],
["edit_media_contents.htm","Edit Media Contents","Edit Media Contents Top Previous Next -Select a specific Media Contents row -Select Edit Contents node -Edit Associated Cases Media is associated ...",""],
["edit_operation_team.htm","Edit Operation Team","Edit Operation Team Top Previous Next -Select Team node -Select Edit tab -Make necessary adjustments -Select Update button Note: All modifications...",""],
["edit_operation_team_services.htm","Edit Operation Team Services","Edit Operation Team Services Top Previous Next -To edit a Service, check the service row item in the grid under Team Services tab. -Select the Edi...",""],
["edit_operation_team_service_tasks.htm","Edit Operation Team Service Tasks","Edit Operation Team Service Tasks Top Previous Next -To edit Services Tasks, Select Edit button under the Service Tasks tab: -Edit Task Name. -Edi...",""],
["edit_operation_team_service_task_subtasks.htm","Edit Operation Team Service Task Subtasks","Edit Operation Team Service Task Subtasks Top Edit Operation Team Service Task Subtasks ",""],
["edit_previewed_invoice.htm","Edit Previewed Invoice","Edit Previewed Invoice Top Previous Next ",""],
["edit_roles.htm","Edit Roles","Edit Roles Top Previous Next -Select User Role node -Edit User Role details -Select Next button -Edit User Role security attributes -Select Update...",""],
["edit_saved_invoices.htm","Edit Saved Invoices","Edit Saved Invoices Top Previous Next ",""],
["edit_shared_pricepoints.htm","Edit Shared Pricepoints","Edit Shared Pricepoints Top Previous Next ",""],
["edit_tax_class.htm","Edit Tax Class","Edit Tax Class Top Previous Next ",""],
["edit_tax_code.htm","Edit Tax Code","Edit Tax Code Top Previous Next ",""],
["edit_team_folder_file_permissions.htm","Edit Team Folder/File Permissions","Edit Team Folder/File Permissions Top Previous Next ",""],
["edit_team_pricepoints.htm","Edit Team Price Points","Edit Team Price Points Top Previous Next ",""],
["edit_users.htm","Edit Users","Edit Users Top Previous Next -Select User node -Edit User details -Select Next button -Edit User Access details -Select Update button -User Securi...",""],
["email_alerts_security.htm","Email Alerts Security","Email Alerts Security Top Email Alerts Security Users can apply administrative security rights on each email alerts. Security can be applied on a ...",""],
["email_alert_configuration.htm","Email Alert Configuration","Email Alert Configuration Top Previous Next The Email Alert Configuation node is designed to display the settings used during the IS-A-TASK instal...",""],
["exclude_team_services.htm","Exclude Team Services","Exclude Team Services Top Previous Next The Exclude Team Services tab allows users to hide specific service tasks from appearin in the New Project...",""],
["filter_projects.htm","Filter Projects","Filter Projects Top Previous Next -Select one or more options in the left section -Select the following icon to apply the filter: -Review results ...",""],
["finalize_invoices.htm","Finalize Invoices","Finalize Invoices Top Previous Next ",""],
["finalize_review_invoices.htm","Finalize Review Invoices","Finalize Review Invoices Top Previous Next ",""],
["generate_invoices.htm","Generate Invoices","Generate Invoices Top Previous Next ",""],
["getting_started.htm","Getting Started","Getting Started Top Previous Next ",""],
["getting_started_submit_new_project_process.htm","Submit New Project Process","Submit New Project Process Top Previous Next The Submit New Project Process: Submit New Project Process Checklist: - Submit New Project ",""],
["global_projects.htm","Global Projects","Global Projects Top Previous Next The Global Project module displays all opened projects across all cases and teams. The module allows users to dy...",""],
["internal_shared_pricing.htm","Internal Shared Pricing","Internal Shared Pricing Top Previous Next ",""],
["internal_team_pricing.htm","Internal Team Pricing","Internal Team Pricing Top Previous Next ",""],
["load_previous_workflow.htm","Load Previous Workflow","Load Previous Workflow Top Previous Next Instead of building custom project workflows as described in the Submit New Case Project section, the use...",""],
["manage_dropdowns.htm","Manage Dropdowns","Manage Dropdowns Top Previous Next There are various system dropdown selection boxes throughout the application and an administrator can adjust th...",""],
["manage_roles.htm","Manage Roles","Manage Roles Top Previous Next The Manage Roles node allows user to create custom roles within the application with its own set of feature securit...",""],
["manage_users.htm","Manage Users","Manage Users Top Previous Next The Manage Users node manages all users that will have access to the system. Addiitional user security attributes m...",""],
["media.htm","Media","Media Top Previous Next The Media module is designed to track all media that can be associated with projects. As users build project workflows, sp...",""],
["media_chain_of_custody.htm","Media Chain of Custody","Media Chain of Custody Top Previous Next The Chain of Custody section allows users to view all transactions that were performed around the Media. ...",""],
["media_check_in_out.htm","Media Check In/out","Media Check In/out Top Previous Next Users can keep track of where each piece of Media is moved to through the Check Out/In feature: -Select one M...",""],
["media_contents.htm","Media Contents","Media Contents Top Previous Next Media Contents is where users list details on what is on the actual Media. Media Contents include Custodian infor...",""],
["media_inventory.htm","Media Inventory","Media Inventory Top Previous Next Media Inventory submodule is where users catelog and manage all of the media and media contents across all proje...",""],
["mycases.htm","My Cases","My Cases Top Previous Next The My Cases module organizes projects by client cases. Each case has its own unique portal where all projects are crea...",""],
["myteams.htm","My Teams","My Teams Top Previous Next ",""],
["my_cases_statistics.htm","My Cases Statistics","My Cases Statistics Top Previous Next The My Cases Statistics areas displays the following project statistics grouped on the case level: -Grid Sta...",""],
["my_cases_system_alerts.htm","My Cases System Alerts","My Cases System Alerts Top Previous Next The My Cases System Alerts notifies the user that the following activity has occurred in one of the cases...",""],
["my_case_portal.htm","My Cases Portal","My Cases Portal Top Previous Next The My Cases Portal is a module where all project activity is organized and managed at the case level. To enter ...",""],
["my_events.htm","My Events","My Events Top Previous Next The My Events section displays projects via their duedate in a calendar view. The user can select any day within the c...",""],
["my_teams_statistics.htm","My Teams Statistics","My Teams Statistics Top Previous Next ",""],
["my_teams_system_alerts.htm","My Teams System Alerts","My Teams System Alerts Top Previous Next ",""],
["my_team_portal.htm","My Team Portal","My Team Portal Top Previous Next ",""],
["operation_team.htm","Operation Team","Operation Team Top Previous Next Operation Teams Workflow - One or more Operation Teams may be created and may consist of internal and/or external...",""],
["operation_teams.htm","Operation Teams","Operation Teams Top Previous Next Operation Team- A Team is an internal or external group that specifically works as unit within your organization...",""],
["operation_team_assigned_users.htm","Operation Team Assigned Users","Operation Team Assigned Users Top Previous Next Assigned Users lists all users that are assigned to the Team: ",""],
["operation_team_services.htm","Operation Team Services","Operation Team Services Top Previous Next Operation Team Services - A Service is a subgroup within a team that have Tasks that are unique to the S...",""],
["operation_team_service_tasks.htm","Operation Team Service Tasks","Operation Team Service Tasks Top Previous Next Operation Team Services Tasks - A Service Task is an activity that needs to be accomplished within ...",""],
["operation_team_service_task_dynamic_subtasks.htm","Operation Team Service Task Dynamic Subtasks","Operation Team Service Task Dynamic Subtasks Top Operation Team Service Task Dynamic Subtasks Service Task Subtasks - Optionally, each Task can co...",""],
["operation_team_service_task_forms.htm","Operation Team Service Task Forms","Operation Team Service Task Forms Top Previous Next Service Tasks Instruction Forms - Optionally, in order for a Team to complete a Task, some Tas...",""],
["operation_team_service_task_subtasks.htm","Operation Team Service Task Subtasks","Operation Team Service Task Subtasks Top Operation Team Service Task Subtasks ",""],
["options.htm","Options","Options Top Previous Next The Options section sets the user preferences across the application. The Options section should be the first area the n...",""],
["paste_case_folder_file.htm","Paste Case Folder/File","Paste Case Folder/File Top Previous Next ",""],
["paste_team_folder_file.htm","Paste Team Folder/File","Paste Team Folder/File Top Previous Next ",""],
["perform_filter_options.htm","Perform Filter Options","Perform Filter Options Top Previous Next -Select Saved Filters submodule -Select one filter at a time on left side to retrieve the selected filter...",""],
["post_case_project_comments.htm","Post Case Project Comments","Post Case Project Comments Top Previous Next ",""],
["post_case_project_comments_2.htm","Post Case Project Comments","Post Case Project Comments Top Previous Next ",""],
["post_team_project_comments.htm","Post Team Project Comments","Post Team Project Comments Top Previous Next ",""],
["post_team_project_comments_2.htm","Post Team Project Comments","Post Team Project Comments Top Previous Next ",""],
["preview_final_invoice.htm","Preview Final Invoice","Preview Final Invoice Top Previous Next ",""],
["pricelist.htm","Price List","Price List Top Previous Next ",""],
["project_attach_media.htm","Project Attach Media","Project Attach Media Top Previous Next The Project Attach Media process allows the user to attach Media and/or related Media Contents directly to ...",""],
["project_estimated_time.htm","Project Estimated Time","Project Estimated Time Top Previous Next The Project Estimated Time feature allows the user to estimate how long a task may take prior to submitti...",""],
["project_sort_display.htm","Project Sort Display","Project Sort Display Top Previous Next The Project Sort Display node is where specific project grids throughout the application are sorted by defa...",""],
["rebrand_system.htm","Rebrand System","Rebrand System Top Previous Next The Rebrand System node allows users to custom brand the application with their company&#39;s logo: There are two are...",""],
["remove_case.htm","Remove Case","Remove Case Top Previous Next -Select a Case node. -Select Delete button under Edit Case tab. Note: A Case cannot be deleted if it is associated w...",""],
["remove_case_contacts.htm","Remove Case Contacts","Remove Case Contacts Top Previous Next -Select a specific Case node. -Select Contacts tab. -Select one or more Contact rows in the grid. -Select R...",""],
["remove_case_manager_team_services.htm","Remove Case Manager Team Services","Remove Case Manager Team Services Top Previous Next -To remove Services, check the service row item in the grid under the Team Services tab. -Sele...",""],
["remove_case_manager_team_service_tasks.htm","Remove Case Manager Team Service Tasks","Remove Case Manager Team Service Tasks Top Previous Next -To remove Tasks, check the Task row item in the grid. -Select the Remove button: -One or...",""],
["remove_case_preferred_rates.htm","Remove Case Preferred Rates","Remove Case Preferred Rates Top Previous Next ",""],
["remove_case_project.htm","Remove Case Project","Remove Case Project Top Previous Next ",""],
["remove_client.htm","Remove Client","Remove Client Top Previous Next -Select a Client node. -Select Delete button under Edit Client tab. Note: A Client cannot be deleted if it has ass...",""],
["remove_client_contacts.htm","Remove Client Contacts","Remove Client Contacts Top Previous Next -Select a specific Client node. -Select Add Contacts tab. -Select one or more Contact rows in the grid. -...",""],
["remove_client_preferred_rates.htm","Remove Client Preferred Rates","Remove Client Preferred Rates Top Previous Next ",""],
["remove_dropdown_item.htm","Remove Dropdown Item","Remove Dropdown Item Top Previous Next -Select Drop-down type -Select a dropdown type value -Select Remove button ",""],
["remove_media_contents.htm","Remove Media Contents","Remove Media Contents Top Previous Next -Select one or more Media Content rows -Select Remove Contents node Note: If a Media Content is already as...",""],
["remove_operation_team.htm","Remove Operation Team","Remove Operation Team Top Previous Next -Select Team node -Select Edit tab -Select Delete button Note: A Team cannot be deleted if there are assoc...",""],
["remove_operation_team_services.htm","Remove Operation Team Services","Remove Operation Team Services Top Previous Next -To remove Services, select a Team node. -Check the service row item in the grid under Team Servi...",""],
["remove_operation_team_service_tasks.htm","Remove Operation Team Service Tasks","Remove Operation Team Service Tasks Top Previous Next -To remove Tasks, check the Task row item in the grid. -Select the Remove button: -One or mo...",""],
["remove_roles.htm","Remove Roles","Remove Roles Top Previous Next -Select User Role node -Select Delete button Note: A role cannot be deleted if it is already associated with a user ",""],
["remove_shared_pricepoints.htm","Remove Shared Pricepoints","Remove Shared Pricepoints Top Previous Next ",""],
["remove_tax_class.htm","Remove Tax Class","Remove Tax Class Top Previous Next ",""],
["remove_tax_code.htm","Remove Tax Code","Remove Tax Code Top Previous Next ",""],
["remove_team_pricepoints.htm","Remove Team Price Points","Remove Team Price Points Top Previous Next ",""],
["remove_users.htm","Remove Users","Remove Users Top Previous Next -Select User Role node -Select Delete button Note: A user cannot be deleted from the application if they are tied t...",""],
["rename_case_folder_file.htm","Rename Case Folder/File","Rename Case Folder/File Top Previous Next ",""],
["rename_team_folder_file.htm","Rename Team Folder/File","Rename Team Folder/File Top Previous Next ",""],
["reopen_closed_case_projects.htm","Reopen Closed Case Projects","Reopen Closed Case Projects Top Previous Next ",""],
["resources.htm","Resources","Resources Top Previous Next The Resources module is an area to quickly gauge the resource level across all case and operation teams: -Task Assignm...",""],
["resubmit_saved_filters.htm","Run Saved Filters","Run Saved Filters Top Previous Next -Select Saved Filters submodule -Select one filter at a time on left side to retrieve the selected filter resu...",""],
["review_invoices.htm","Review Invoices","Review Invoices Top Previous Next ",""],
["run_saved_invoices.htm","Run Saved Invoices","Run Saved Invoices Top Previous Next ",""],
["saved_filters.htm","Saved Filters","Saved Filters Top Previous Next The Saved Filters submodule allow users to manage all saved filters and rerun the filter to retreive new results. ...",""],
["saved_invoices.htm","Saved Invoices","Saved Invoices Top Previous Next ",""],
["save_filtered_projects.htm","Save Filtered Projects","Save Filtered Projects Top Save Filtered Projects ",""],
["save_review_invoices.htm","Save Review Invoices","Save Review Invoices Top Previous Next ",""],
["search_case_folder_file.htm","Search Case Folder/File","Search Case Folder/File Top Previous Next ",""],
["search_case_projects.htm","Search Case Projects","Search Case Projects Top Previous Next The Search Case Projects feature allow the user to select one or more active cases and perform keyword sear...",""],
["search_team_folder_file.htm","Search Team Folder/File","Search Team Folder/File Top Previous Next ",""],
["search_team_projects.htm","Search Team Projects","Search Team Projects Top Previous Next ",""],
["session_timeout_preference.htm","Session Timeout Preference","Session Timeout Preference Top Previous Next Session Timeout allows a user to set the time the application auto logs out. -Select the Options icon...",""],
["single_export_previewed_invoice.htm","Single Export Previewed Invoice","Single Export Previewed Invoice Top Previous Next ",""],
["statistics.htm","Statistics","Statistics Top Previous Next ",""],
["submit_new_project.htm","Submit New Case Project","Submit New Case Project Top Previous Next The Submit New Project process can only be achieved in the My Cases module under a specific Case portal....",""],
["submit_saved_case_projects.htm","Submit Saved Case Projects","Submit Saved Case Projects Top Previous Next The Submit Saved Case Projects feature allows the user to retrieve previously saved projects to conti...",""],
["subscribe_to_email_alerts.htm","Subscribe To Email Alerts","Subscribe To Email Alerts Top Previous Next Each user has the ability to subscribe to email alerts based on various activities performed throughou...",""],
["supported_browsers.htm","Supported Browsers","Supported Browsers Top Previous Next -Firefox (v23.00 and greater (recommended)) -Chrome (v25.00 and greater) -IE10 (recommended over IE9) -IE9 -S...",""],
["system_management.htm","System Management","System Management Top Previous Next The System Management is a submodule that allows the user to custom configure system wide feature functionalit...",""],
["system_updates.htm","System Updates","System Updates Top Previous Next The System Updates node allows users to update IS-A-TASK with all system updates. Refer to the IS-A-TASK New Rele...",""],
["task_assignments.htm","Task Assignments","Task Assignments Top Previous Next The Task Assignments submodule to view what and how many active tasks users are assigned: -Select Task Assignme...",""],
["taxes.htm","Taxes","Taxes Top Previous Next ",""],
["tax_classes.htm","Tax Classes","Tax Classes Top Previous Next ",""],
["tax_codes.htm","Tax Codes","Tax Codes Top Previous Next ",""],
["teams_workflow_setup.htm","Teams Workflow Setup","Teams Workflow Setup Top Previous Next Teams workflow must be setup in the Administration module prior to using IS-A-TASK: The definition of Workf...",""],
["team_assignments_status_grid.htm","Team Assignments Status Grid","Team Assignments Status Grid Top Previous Next My Teams Assignments tab indicates the logged in user&#39;s assignments that relate to a Operation team...",""],
["team_billable_items.htm","Team Billable Items","Team Billable Items Top Previous Next ",""],
["team_custodians_subtasks.htm","Team Custodian Subtasks","Team Custodian Subtasks Top Previous Next ",""],
["team_documents.htm","Team Documents","Team Documents Top Previous Next ",""],
["team_projects.htm","Team Projects","Team Projects Top Previous Next ",""],
["team_project_grid.htm","Team Project Grid","Team Project Grid Top Previous Next ",""],
["team_project_instructions.htm","Team Project Instructions","Team Project Instructions Top Previous Next ",""],
["team_project_status_grid.htm","Team Project Status Grid","Team Project Status Grid Top Previous Next ",""],
["team_project_transaction_activity.htm","Team Project Transaction Activity","Team Project Transaction Activity Top Previous Next ",""],
["team_reports.htm","Team Reports","Team Reports Top Previous Next ",""],
["team_task_assignments.htm","Team Task Assignments","Team Task Assignments Top Previous Next ",""],
["team_task_grid.htm","Team Task Grid","Team Task Grid Top Previous Next ",""],
["team_task_status.htm","Team Task Status","Team Task Status Top Previous Next ",""],
["team_todo_items.htm","Team ToDo Items","Team ToDo Items Top Previous Next ",""],
["technical_support.htm","Technical Support","Technical Support Top Previous Next Contact Inovitech support team to assist with technical issues: Email: support@inovitech.com Phone: 877-429-03...",""],
["timezone_preference.htm","Timezone Preference","Timezone Preference Top Previous Next Setting the Timezone Preference will change all of the dates throughout the system dynamically be displayed ...",""],
["todays_activity.htm","Today&#39;s Activity","Today&#39;s Activity Top Previous Next The Today&#39;s Activity section list specific activities users perform across the application regarding the cases ...",""],
["total_case_project_time_by_task.htm","Total Case Project Time By Task","Total Case Project Time By Task Top Previous Next ",""],
["track_case_project.htm","Track Case Project","Track Case Project Top Previous Next The Track Case Project submodule is where users track the progress of the actual project tasks. A project con...",""],
["track_team_project.htm","Track Team Project","Track Team Project Top Previous Next ",""],
["upload_case_file.htm","Upload Case File","Upload Case File Top Previous Next ",""],
["upload_team_file.htm","Upload Team File","Upload Team File Top Previous Next ",""],
["user_management.htm","User Management","User Management Top Previous Next The User Management is a submodule designed to manage all of your users and user roles: -Manage Roles -Manage Us...",""],
["user_security.htm","User Security","User Security Top Previous The User Security tab is part of the Edit User process. This tab allows the user to have additional feature rights that...",""],
["user_setup.htm","User Setup","User Setup Top Previous Next User Roles and Users must be setup in the Administration module prior to using IS-A-TASK: The User Setup Process: Rol...",""],
["view_associated_cases.htm","View Associated Cases","View Associated Cases Top Previous Next Since one piece of Media can be associated with one or more cases and/or clients, the View Associated Case...",""],
["workflow_management.htm","Workflow Management","Workflow Management Top Previous Next The Workflow Management submodule is the area where users setup the workflow requirements of their organizat...",""]];
